################################################################################
#                                                                              #
#   Efficient matrix inversion demonstration that offers two tools:            #
#                                                                              #
#     solve_list <- makeCacheMatrix(m = matrix()): Returns a list of functions #
#            for setting, storing and referencing the supplied matrix and its  #
#	     previously calculated inverse.                                    #
#                                                                              #
#     solve_mat <- cacheSolve(solve_list): Returns the inverse of the matrix   #
#            associated with the list generated by 'makeCacheMatrix' above.    #
#                                                                              #
#   Notes: These two functions were designed to be used together to quickly    #
#          and repeatedly calculate the inverse of the supplied matrix.  An    #
#          initial call to 'makeCacheMatrix' can be followed by any number of  #
#          calls to 'cacheSolve':                                              #
#                                                                              #
#                   $ solve_list <- makeCacheMatrix(m)                         #
#                   $ solve_mat <- cacheSolve(solve_list)                      #
#                   $        ...                                               #
#                   $ solve_mat <- cacheSolve(solve_list)                      #
#                                                                              #
#          First 'cacheSolve' call calculates, cache-saves, returns the inv    #
#                of the user supplied matrix to 'makeCacheMatrix'.             #
#          Subsequent 'cacheSolve' calls return the cache-saved result.        #
#                                                                              #
#   Harry J. Reed - Data Science, R Class, Pgm Assignment 2 - 18 MAR 2015      #
#                                                                              #      
################################################################################

################################################################################
#  FUNCTION   makeCacheMatrix                                                  #
#      Inputs:  Matrix 'm' to be inverted later. Default m = matrix().         #
#      Outputs: Function list to set, store, and reference the supplied matrix #
#                     and its inverse.                                         #
#      Usage:   $ solve_list <- makeCacheMatrix(m = matrix())                  #
#      Note:    This function was designed to be used with 'cacheSolve' below. #
#               The output of this function serves as input to 'cacheSolve'.   #
################################################################################
makeCacheMatrix <- function(tmp_mat = matrix()) {

 	cached_mat <- tmp_mat			  ## Supplied matrix cache
        cached_solve <- NULL			  ## Inverted matrix calc cache

        set <- function(tmp_mat) {		  ## FUNCTION set
                cached_mat <<- tmp_mat		    ## Save supplied matrix
                cached_solve <<- NULL		    ## & note no inv pre-exists 
		## return()
        }

        get <- function() {			  ## FUNCTION get
		return(cached_mat)		    ## Return supplied matrix
	}

        setsolve <- function(solve) {		  ## FUNCTION setsolve
		cached_solve <<- solve		    ## Save supplied matrix inv
		## return()
	}

        getsolve <- function() {		  ## FUNCTION getsolve
		return(cached_solve)		    ## Return matrix inverse
	}
        
	return(	
		list(	set = set, get = get,	  ## Return list of functions to
			setsolve = setsolve,	  ## set, get the matrix and
			getsolve = getsolve )	  ## set, get the matrix inverse
	)

}   ## End of function makeCacheMatrix


################################################################################
#  FUNCTION   cacheSolve                                                       #
#      Inputs:  Function list first created by 'makeCacheMatrix' acting on a   #
#                     user supplied matrix (please see above).                 #
#      Outputs: The inverse of the user supplied matrix to 'makeCacheMatrix'.  #
#      Usage:   $ solve_mat <- cacheSolve(solve_list)                          #
#      Note:    This function was designed to be used with 'makeCacheMatrix'.  #
################################################################################
cacheSolve <- function(tmp_solve_list, ...) {

        cur_solve <- tmp_solve_list$getsolve()	   ## Get prev inv calc (if any)

        if(!is.null(cur_solve)) {
                message("getting cached data")	   ## Prev inv exists, no re-calc
        } else {
        	tmp_mat <- tmp_solve_list$get()	   ## Prev inv not exists, so
        	cur_solve <- solve(tmp_mat, ...)   ## calc matrix inverse and
        	tmp_solve_list$setsolve(cur_solve) ## save for future ref.
	}

                return(cur_solve)		   # Return matrix inverse.

}   ## End of function cacheSolve
